export type AdminCrudFieldType =
  | "text"
  | "textarea"
  | "number"
  | "date"
  | "datetime"
  | "select"
  | "switch"
  | "image"
  | "file"
  | "gallery"
  | "files"
  | "links";

export type AdminCrudValue = string | number | boolean | null;

export type AdminCrudOption = {
  value: string;
  label: string;
};

export type AdminCrudField = {
  name: string;
  label: string;
  type: AdminCrudFieldType;
  required?: boolean;
  defaultValue?: AdminCrudValue;
  options?: AdminCrudOption[];
  placeholder?: string;
  description?: string;
  span?: "full" | "half";
  optionalColumn?: boolean;
  hidden?: boolean;
  autoGenerate?: "slug";
  sourceField?: string;
  uploadFolder?: "images" | "news" | "personnel" | "documents";
  uploadHint?: string;
  optionsSource?: "news_categories" | "document_categories";
};

export type AdminCrudModuleConfig = {
  key: string;
  label: string;
  table: string;
  permission: string;
  titleField: string;
  descriptionField?: string;
  categoryField?: string;
  statusField?: string;
  metricField?: string;
  metricSuffix?: string;
  hrefField?: string;
  hrefTemplate?: string;
  hrefFallback?: string;
  normalizeHref?: boolean;
  orderBy?: string;
  uniqueFields?: string[];
  createdAt?: boolean;
  updatedAt?: boolean;
  fields: AdminCrudField[];
};

export type AdminCrudRow = {
  id: number;
  title: string;
  description?: string;
  category?: string;
  href: string;
  status?: string;
  metric?: string;
  values: Record<string, AdminCrudValue>;
};

export const publishedStatusOptions: AdminCrudOption[] = [
  { value: "published", label: "เผยแพร่" },
  { value: "draft", label: "ร่าง" },
  { value: "review", label: "รอตรวจ" },
  { value: "archived", label: "เก็บถาวร" },
];

export const activeStatusOptions: AdminCrudOption[] = [
  { value: "active", label: "เปิดใช้งาน" },
  { value: "inactive", label: "ปิดใช้งาน" },
];

const commonPublishedField: AdminCrudField = {
  name: "status",
  label: "สถานะ",
  type: "select",
  defaultValue: "published",
  options: publishedStatusOptions,
};

const commonActiveField: AdminCrudField = {
  name: "status",
  label: "สถานะ",
  type: "select",
  defaultValue: "active",
  options: activeStatusOptions,
};

export const adminCrudConfigs: AdminCrudModuleConfig[] = [
  {
    key: "content_pages",
    label: "หน้าเนื้อหาเว็บไซต์",
    table: "content_pages",
    permission: "content_pages",
    titleField: "title",
    descriptionField: "summary",
    categoryField: "nav_key",
    statusField: "status",
    metricField: "slug",
    hrefTemplate: "/content/{slug}",
    hrefFallback: "/",
    orderBy: "ORDER BY updated_at DESC, id DESC",
    uniqueFields: ["slug"],
    createdAt: true,
    updatedAt: true,
    fields: [
      { name: "title", label: "หัวข้อ", type: "text", required: true },
      { name: "slug", label: "URL slug", type: "text", required: true, hidden: true, autoGenerate: "slug", sourceField: "title", placeholder: "administrative-structure" },
      { name: "content_type", label: "ชนิดหน้า", type: "text", optionalColumn: true, placeholder: "general / structure / people / ita" },
      { name: "nav_key", label: "ผูกกับเมนูหลัก", type: "text", placeholder: "about" },
      { name: "summary", label: "คำอธิบายสั้น", type: "textarea", span: "full" },
      { name: "body", label: "เนื้อหา", type: "textarea", span: "full" },
      { name: "cover_image", label: "ภาพประกอบ / ภาพผัง", type: "image", uploadFolder: "images", optionalColumn: true },
      { name: "attachment_path", label: "ไฟล์แนบ / เอกสาร", type: "file", uploadFolder: "documents", optionalColumn: true },
      { name: "source_url", label: "ลิงก์ต้นฉบับ / ลิงก์อ้างอิง", type: "text", optionalColumn: true },
      commonPublishedField,
    ],
  },
  {
    key: "navigation_items",
    label: "เมนู Navbar",
    table: "navigation_items",
    permission: "cms.navbar",
    titleField: "label",
    categoryField: "item_key",
    statusField: "is_active",
    metricField: "url",
    hrefField: "url",
    hrefFallback: "/",
    normalizeHref: true,
    orderBy: "ORDER BY COALESCE(parent_id, id), sort_order, id",
    uniqueFields: ["item_key"],
    createdAt: true,
    updatedAt: true,
    fields: [
      { name: "parent_id", label: "ID เมนูแม่", type: "number", placeholder: "เว้นว่างสำหรับเมนูหลัก" },
      { name: "label", label: "ชื่อเมนู", type: "text", required: true },
      { name: "url", label: "ลิงก์", type: "text", required: true, placeholder: "/about หรือ https://..." },
      { name: "item_key", label: "รหัสเมนู", type: "text", placeholder: "about" },
      { name: "sort_order", label: "ลำดับ", type: "number", defaultValue: 0 },
      { name: "is_active", label: "เปิดใช้งาน", type: "switch", defaultValue: true },
    ],
  },
  {
    key: "quick_links",
    label: "ลิงก์ด่วน / eService",
    table: "quick_links",
    permission: "cms.quick_links",
    titleField: "label",
    categoryField: "item_key",
    statusField: "is_active",
    metricField: "url",
    hrefField: "url",
    hrefFallback: "/",
    normalizeHref: true,
    orderBy: "ORDER BY sort_order, id",
    uniqueFields: ["item_key"],
    createdAt: true,
    updatedAt: true,
    fields: [
      { name: "label", label: "ชื่อบริการ / ลิงก์", type: "text", required: true },
      { name: "url", label: "ลิงก์", type: "text", required: true, placeholder: "https://... หรือ /services" },
      { name: "item_key", label: "รหัสลิงก์", type: "text", placeholder: "rms" },
      { name: "sort_order", label: "ลำดับ", type: "number", defaultValue: 0 },
      { name: "is_active", label: "เปิดใช้งาน", type: "switch", defaultValue: true },
    ],
  },
  {
    key: "site_blocks",
    label: "แบนเนอร์และข้อความหน้าเว็บ",
    table: "site_blocks",
    permission: "site_blocks",
    titleField: "title",
    descriptionField: "subtitle",
    categoryField: "block_key",
    statusField: "status",
    hrefFallback: "/",
    orderBy: "ORDER BY block_key, id",
    uniqueFields: ["block_key"],
    createdAt: true,
    updatedAt: true,
    fields: [
      { name: "block_key", label: "รหัสบล็อก", type: "text", required: true, placeholder: "home_hero" },
      { name: "title", label: "หัวข้อ", type: "text", required: true },
      { name: "subtitle", label: "คำโปรย", type: "textarea", span: "full" },
      { name: "body", label: "รายละเอียด", type: "textarea", span: "full" },
      {
        name: "image_path",
        label: "ภาพประกอบ",
        type: "image",
        uploadFolder: "images",
        placeholder: "assets/images/hero-campus.png",
        span: "full",
        uploadHint: "ภาพ Hero แนะนำขนาด 1920 x 720 px หรืออัตราส่วนประมาณ 8:3 ใช้ JPG/WebP ไม่เกิน 2 MB และวางจุดสำคัญของภาพไว้ฝั่งขวาเพื่อไม่ชนข้อความ",
      },
      { name: "primary_label", label: "ปุ่มหลัก", type: "text" },
      { name: "primary_url", label: "ลิงก์ปุ่มหลัก", type: "text" },
      { name: "secondary_label", label: "ปุ่มรอง", type: "text" },
      { name: "secondary_url", label: "ลิงก์ปุ่มรอง", type: "text" },
      { name: "tertiary_label", label: "ปุ่มที่สาม", type: "text" },
      { name: "tertiary_url", label: "ลิงก์ปุ่มที่สาม", type: "text" },
      commonActiveField,
    ],
  },
  {
    key: "course_groups",
    label: "หลักสูตรและแผนกวิชา",
    table: "course_groups",
    permission: "course_groups",
    titleField: "title",
    descriptionField: "description",
    categoryField: "level_label",
    statusField: "status",
    metricField: "courses_text",
    hrefFallback: "/departments",
    orderBy: "ORDER BY sort_order, id",
    createdAt: true,
    updatedAt: true,
    fields: [
      { name: "level_label", label: "ระดับหลักสูตร", type: "text", required: true, placeholder: "ปวช." },
      { name: "title", label: "ชื่อกลุ่มหลักสูตร", type: "text", required: true },
      { name: "description", label: "คำอธิบาย", type: "textarea", span: "full" },
      { name: "courses_text", label: "รายชื่อแผนก / หลักสูตร", type: "textarea", span: "full", description: "ใส่ 1 รายการต่อ 1 บรรทัด" },
      { name: "course_links_text", label: "ลิงก์เว็บไซต์แผนก", type: "textarea", span: "full", optionalColumn: true, description: "รูปแบบ: ชื่อแผนก | ลิงก์" },
      { name: "sort_order", label: "ลำดับ", type: "number", defaultValue: 0 },
      commonActiveField,
    ],
  },
  {
    key: "student_stats",
    label: "ยอดผู้เรียน",
    table: "student_stats",
    permission: "student_stats",
    titleField: "label",
    categoryField: "academic_year",
    statusField: "status",
    metricField: "stat_value",
    hrefFallback: "/",
    orderBy: "ORDER BY sort_order, id",
    createdAt: true,
    updatedAt: true,
    fields: [
      { name: "label", label: "ชื่อสถิติ", type: "text", required: true },
      { name: "academic_year", label: "ปีการศึกษา", type: "text", optionalColumn: true, placeholder: "2569" },
      { name: "stat_value", label: "จำนวน", type: "number", required: true, defaultValue: 0 },
      { name: "sort_order", label: "ลำดับ", type: "number", defaultValue: 0 },
      commonActiveField,
    ],
  },
  {
    key: "student_enrollments",
    label: "ผู้เรียน ปวช./ปวส. รายปี",
    table: "student_enrollments",
    permission: "student_stats",
    titleField: "department_name",
    descriptionField: "note",
    categoryField: "academic_year",
    statusField: "status",
    metricField: "actual_count",
    metricSuffix: "คน",
    hrefFallback: "/students#student-data",
    orderBy: "ORDER BY academic_year DESC, sort_order, level_label, department_name, id",
    createdAt: true,
    updatedAt: true,
    fields: [
      { name: "academic_year", label: "ปีการศึกษา", type: "text", required: true, placeholder: "2569", description: "ข้อมูลผู้เรียนจะผูกกับปีการศึกษานี้ และหน้าเว็บจะแสดงตามปีที่เลือก" },
      { name: "report_date", label: "วันที่รายงาน", type: "date", optionalColumn: true, description: "เช่น วันที่ในหนังสือรายงานจำนวนนักเรียน" },
      {
        name: "level_label",
        label: "ระดับ",
        type: "select",
        required: true,
        defaultValue: "ปวช.1",
        options: [
          { value: "ปวช.1", label: "ปวช.1" },
          { value: "ปวช.2", label: "ปวช.2" },
          { value: "ปวช.3", label: "ปวช.3" },
          { value: "ปวส.ทวิ ปี 1", label: "ปวส.ทวิ ปี 1" },
          { value: "ปวส.ทวิ ปี 2", label: "ปวส.ทวิ ปี 2" },
          { value: "ปวส.ภาคสมทบ ปี 1", label: "ปวส.ภาคสมทบ ปี 1" },
          { value: "ปวส.ภาคสมทบ ปี 2", label: "ปวส.ภาคสมทบ ปี 2" },
        ],
        description: "ระบบจะแยกคอลัมน์ ปวส. เป็น ทวิปี 1-2 และภาคสมทบปี 1-2 บนหน้าเว็บอัตโนมัติ",
      },
      { name: "department_name", label: "แผนกวิชา / สาขา / กลุ่มเรียน", type: "text", required: true, placeholder: "ช่างยนต์ 1/1, การบัญชี ทวิ หรือ การบัญชี ภาคสมทบ" },
      { name: "student_count", label: "จำนวนตามบัญชีทั้งหมด", type: "number", required: true, defaultValue: 0, description: "ยอดผู้เรียนทั้งหมดตามรายงาน" },
      { name: "actual_count", label: "จำนวนมีตัวตนจริง", type: "number", defaultValue: 0, optionalColumn: true, description: "ยอดที่ใช้แสดงเป็นจำนวนผู้เรียนหลักบนหน้าเว็บ" },
      { name: "registered_count", label: "ลงทะเบียนเรียนแล้ว", type: "number", defaultValue: 0, optionalColumn: true },
      { name: "unregistered_count", label: "ยังไม่ลงทะเบียน", type: "number", defaultValue: 0, optionalColumn: true },
      { name: "repeat_count", label: "เรียนซ้ำ", type: "number", defaultValue: 0, optionalColumn: true },
      { name: "credit_collect_count", label: "เก็บรายวิชา", type: "number", defaultValue: 0, optionalColumn: true },
      { name: "male_count", label: "ชาย", type: "number", defaultValue: 0, optionalColumn: true },
      { name: "female_count", label: "หญิง", type: "number", defaultValue: 0, optionalColumn: true },
      { name: "note", label: "หมายเหตุ", type: "textarea", span: "full", optionalColumn: true },
      { name: "sort_order", label: "ลำดับ", type: "number", defaultValue: 0 },
      commonActiveField,
    ],
  },
  {
    key: "short_course_enrollments",
    label: "ผู้เรียนหลักสูตรระยะสั้น",
    table: "short_course_enrollments",
    permission: "student_stats",
    titleField: "course_name",
    descriptionField: "note",
    categoryField: "academic_year",
    statusField: "status",
    metricField: "learner_count",
    metricSuffix: "คน",
    hrefFallback: "/students?tab=short#student-data",
    orderBy: "ORDER BY academic_year DESC, sort_order, department_name, course_name, id",
    createdAt: true,
    updatedAt: true,
    fields: [
      { name: "academic_year", label: "ปีการศึกษา", type: "text", required: true, placeholder: "2569" },
      { name: "term_label", label: "ภาคเรียน / ช่วงเวลา", type: "text", optionalColumn: true, placeholder: "1/2569 หรือ รุ่น 1" },
      { name: "department_name", label: "ฝ่ายงาน / แผนกที่รับผิดชอบ", type: "text", optionalColumn: true, placeholder: "งานหลักสูตรระยะสั้น / แผนกช่างยนต์" },
      { name: "course_name", label: "ชื่อรายวิชา / หลักสูตร", type: "text", required: true },
      { name: "batch_label", label: "รุ่น / รอบเรียน", type: "text", optionalColumn: true, placeholder: "รุ่นที่ 1 / รอบวันเสาร์-อาทิตย์" },
      { name: "hours", label: "จำนวนชั่วโมง", type: "number", defaultValue: 0, optionalColumn: true },
      { name: "learner_count", label: "จำนวนผู้เรียน", type: "number", required: true, defaultValue: 0 },
      { name: "completed_count", label: "สำเร็จหลักสูตร", type: "number", defaultValue: 0, optionalColumn: true },
      { name: "certificate_count", label: "ได้รับใบประกาศ", type: "number", defaultValue: 0, optionalColumn: true },
      { name: "male_count", label: "ชาย", type: "number", defaultValue: 0, optionalColumn: true },
      { name: "female_count", label: "หญิง", type: "number", defaultValue: 0, optionalColumn: true },
      { name: "start_date", label: "วันที่เริ่ม", type: "date", optionalColumn: true },
      { name: "end_date", label: "วันที่สิ้นสุด", type: "date", optionalColumn: true },
      { name: "instructor_name", label: "ผู้สอน / ผู้รับผิดชอบ", type: "text", optionalColumn: true },
      { name: "note", label: "รายละเอียดเพิ่มเติม", type: "textarea", span: "full", optionalColumn: true },
      { name: "sort_order", label: "ลำดับ", type: "number", defaultValue: 0 },
      commonActiveField,
    ],
  },
  {
    key: "personnel_profiles",
    label: "บุคลากร / คณะกรรมการ",
    table: "personnel_profiles",
    permission: "personnel",
    titleField: "full_name",
    descriptionField: "position_title",
    categoryField: "section_title",
    statusField: "status",
    metricField: "department",
    hrefTemplate: "/content/{page_slug}",
    hrefFallback: "/about",
    orderBy: "ORDER BY page_slug, sort_order, id",
    createdAt: true,
    updatedAt: true,
    fields: [
      { name: "page_slug", label: "หน้าที่แสดงผล", type: "text", required: true, placeholder: "administrators" },
      { name: "section_title", label: "หัวข้อกลุ่ม", type: "text", placeholder: "ผู้บริหาร" },
      { name: "full_name", label: "ชื่อ-สกุล", type: "text", required: true },
      { name: "position_title", label: "ตำแหน่ง", type: "textarea", required: true, span: "full" },
      { name: "department", label: "ฝ่าย / แผนก", type: "text" },
      { name: "committee_role", label: "บทบาทในคณะกรรมการ", type: "text", optionalColumn: true, placeholder: "ประธานกรรมการ / กรรมการ / เลขานุการ" },
      { name: "contact_phone", label: "เบอร์โทรติดต่อ", type: "text", optionalColumn: true, placeholder: "044-514414 ต่อ ..." },
      { name: "contact_email", label: "อีเมลติดต่อ", type: "text", optionalColumn: true, placeholder: "name@srpoly.ac.th" },
      { name: "contact_channel", label: "ช่องทางติดต่อเพิ่มเติม", type: "text", optionalColumn: true, placeholder: "Line / Facebook / ห้องสำนักงาน" },
      { name: "term_period", label: "วาระ / ช่วงปี", type: "text", optionalColumn: true, placeholder: "พ.ศ. 2568-2570" },
      {
        name: "photo_path",
        label: "รูปภาพ",
        type: "image",
        uploadFolder: "personnel",
        placeholder: "assets/images/personnel/name.jpg",
        uploadHint: "แนะนำภาพบุคคลแนวตั้ง อัตราส่วนประมาณ 4:5 หรือ 3:4 ขนาดอย่างน้อย 900 x 1200 px ไฟล์ JPG/PNG/WebP ไม่เกิน 15 MB",
      },
      { name: "appointment_file", label: "ไฟล์คำสั่งแต่งตั้ง / เอกสารอ้างอิง", type: "file", uploadFolder: "documents", optionalColumn: true, placeholder: "/uploads/documents/appointment.pdf" },
      { name: "profile_note", label: "รายละเอียดหน้าที่ / หมายเหตุ", type: "textarea", span: "full", optionalColumn: true },
      { name: "sort_order", label: "ลำดับ", type: "number", defaultValue: 0 },
      commonActiveField,
    ],
  },
  {
    key: "personnel_summary_stats",
    label: "สรุปจำนวนบุคลากร",
    table: "personnel_summary_stats",
    permission: "personnel",
    titleField: "personnel_type",
    descriptionField: "context_note",
    categoryField: "academic_year",
    statusField: "status",
    metricField: "staff_count",
    metricSuffix: "คน",
    hrefFallback: "/content/personnel-data",
    orderBy: "ORDER BY academic_year DESC, sort_order, personnel_type, id",
    createdAt: true,
    updatedAt: true,
    fields: [
      { name: "academic_year", label: "ปีการศึกษา", type: "text", required: true, placeholder: "2569" },
      { name: "personnel_type", label: "ประเภทบุคลากร", type: "text", required: true, placeholder: "ข้าราชการครู / เจ้าหน้าที่สนับสนุน" },
      { name: "department", label: "กลุ่มงาน / สายงาน", type: "text", optionalColumn: true },
      { name: "staff_count", label: "จำนวน", type: "number", required: true, defaultValue: 0 },
      { name: "context_note", label: "บริบท / หมายเหตุ", type: "textarea", span: "full", optionalColumn: true },
      { name: "sort_order", label: "ลำดับ", type: "number", defaultValue: 0 },
      commonActiveField,
    ],
  },
  {
    key: "personnel_layouts",
    label: "เลย์เอาต์บุคลากร",
    table: "personnel_page_layouts",
    permission: "personnel",
    titleField: "heading",
    descriptionField: "summary",
    categoryField: "page_slug",
    statusField: "status",
    metricField: "columns_desktop",
    hrefTemplate: "/content/{page_slug}",
    hrefFallback: "/about",
    orderBy: "ORDER BY page_slug, id",
    uniqueFields: ["page_slug"],
    createdAt: true,
    updatedAt: true,
    fields: [
      { name: "page_slug", label: "หน้าที่แสดงผล", type: "text", required: true, placeholder: "administrators" },
      { name: "eyebrow", label: "ข้อความเหนือหัวข้อ", type: "text" },
      { name: "heading", label: "หัวข้อหน้า", type: "text", required: true },
      { name: "summary", label: "คำอธิบาย", type: "textarea", span: "full" },
      { name: "columns_desktop", label: "จำนวนคอลัมน์บนเดสก์ท็อป", type: "number", defaultValue: 4 },
      {
        name: "card_style",
        label: "รูปแบบการ์ด",
        type: "select",
        defaultValue: "standard",
        options: [
          { value: "standard", label: "มาตรฐาน" },
          { value: "compact", label: "กระชับ" },
        ],
      },
      {
        name: "image_shape",
        label: "รูปทรงภาพ",
        type: "select",
        defaultValue: "circle",
        options: [
          { value: "circle", label: "วงกลม" },
          { value: "rounded", label: "มุมโค้ง" },
          { value: "square", label: "สี่เหลี่ยม" },
        ],
      },
      { name: "show_section_title", label: "แสดงหัวข้อกลุ่ม", type: "switch", defaultValue: true },
      { name: "show_department", label: "แสดงฝ่าย / แผนก", type: "switch", defaultValue: true },
      commonActiveField,
    ],
  },
  {
    key: "news_categories",
    label: "หมวดข่าว",
    table: "categories",
    permission: "news",
    titleField: "name",
    descriptionField: "description",
    categoryField: "slug",
    statusField: "status",
    hrefFallback: "/news",
    orderBy: "WHERE type = 'news' ORDER BY sort_order, id",
    uniqueFields: ["slug"],
    fields: [
      { name: "name", label: "ชื่อหมวดข่าว", type: "text", required: true, placeholder: "ประชาสัมพันธ์ทั่วไป" },
      { name: "slug", label: "รหัสหมวด", type: "text", required: true, hidden: true, autoGenerate: "slug", sourceField: "name", placeholder: "general" },
      {
        name: "type",
        label: "ชนิดหมวด",
        type: "select",
        hidden: true,
        defaultValue: "news",
        options: [{ value: "news", label: "ข่าว" }],
      },
      { name: "description", label: "คำอธิบาย", type: "textarea", span: "full" },
      { name: "sort_order", label: "ลำดับ", type: "number", defaultValue: 0 },
      commonActiveField,
    ],
  },
  {
    key: "document_categories",
    label: "หมวดดาวน์โหลดเอกสาร",
    table: "categories",
    permission: "documents",
    titleField: "name",
    descriptionField: "description",
    categoryField: "slug",
    statusField: "status",
    hrefFallback: "/documents",
    orderBy: "WHERE type = 'document' ORDER BY sort_order, id",
    uniqueFields: ["slug"],
    fields: [
      { name: "name", label: "ชื่อหมวดเอกสาร", type: "text", required: true, placeholder: "แบบฟอร์มงานทะเบียน" },
      { name: "slug", label: "รหัสหมวด", type: "text", required: true, hidden: true, autoGenerate: "slug", sourceField: "name", placeholder: "registration-forms" },
      {
        name: "type",
        label: "ชนิดหมวด",
        type: "select",
        hidden: true,
        defaultValue: "document",
        options: [{ value: "document", label: "ดาวน์โหลดเอกสาร" }],
      },
      { name: "description", label: "คำอธิบาย", type: "textarea", span: "full" },
      { name: "sort_order", label: "ลำดับ", type: "number", defaultValue: 0 },
      commonActiveField,
    ],
  },
  {
    key: "news",
    label: "ข่าวประชาสัมพันธ์",
    table: "news",
    permission: "news",
    titleField: "title",
    descriptionField: "summary",
    categoryField: "category_id",
    statusField: "status",
    metricField: "view_count",
    hrefTemplate: "/news/{slug}",
    hrefFallback: "/news",
    orderBy: "ORDER BY COALESCE(published_at, created_at) DESC, id DESC",
    uniqueFields: ["slug"],
    createdAt: true,
    updatedAt: true,
    fields: [
      { name: "title", label: "หัวข้อข่าว", type: "text", required: true },
      { name: "slug", label: "URL slug", type: "text", required: true, hidden: true, autoGenerate: "slug", sourceField: "title", placeholder: "news-title" },
      { name: "category_id", label: "หมวดข่าว", type: "select", optionsSource: "news_categories" },
      {
        name: "cover_image",
        label: "ภาพปก",
        type: "image",
        uploadFolder: "news",
        placeholder: "assets/images/news.jpg",
        uploadHint: "ภาพปกข่าวแนะนำ 1200 x 675 px อัตราส่วน 16:9 ใช้ JPG/WebP เพื่อให้ภาพเด่นและรายการข่าวแสดงสวยเท่ากัน",
      },
      {
        name: "gallery_images",
        label: "ภาพประกอบข่าวหลายภาพ",
        type: "gallery",
        uploadFolder: "news",
        span: "full",
        optionalColumn: true,
        uploadHint: "ภาพประกอบข่าวแนะนำกว้างอย่างน้อย 1200 px ใช้ JPG/WebP และเลือกภาพชุดเดียวกันเพื่อให้กริดภาพย่อดูสม่ำเสมอ",
        description: "อัปโหลดภาพกิจกรรมหรือภาพประกอบได้หลายภาพ ระบบจะแสดงเป็นกริดภาพย่อในหน้าข่าว",
      },
      { name: "summary", label: "คำอธิบายสั้น", type: "textarea", span: "full" },
      { name: "content", label: "เนื้อหาข่าว", type: "textarea", span: "full" },
      {
        name: "attachment_files",
        label: "ไฟล์แนบ / PDF / เอกสารดาวน์โหลด",
        type: "files",
        uploadFolder: "documents",
        span: "full",
        optionalColumn: true,
        description: "แนบ PDF, Word, Excel, PowerPoint, ZIP หรือรูปภาพได้หลายไฟล์ ผู้อ่านจะดาวน์โหลดได้จากหน้าข่าว",
      },
      {
        name: "external_links",
        label: "ลิงก์ที่เกี่ยวข้อง",
        type: "links",
        span: "full",
        optionalColumn: true,
        description: "ใส่ 1 รายการต่อ 1 บรรทัด เช่น ชื่อเว็บไซต์ | https://example.com",
      },
      {
        name: "sync_to_downloads",
        label: "แสดงไฟล์แนบข่าวในเมนูดาวน์โหลดเอกสาร",
        type: "switch",
        defaultValue: true,
        optionalColumn: true,
      },
      { name: "is_featured", label: "แสดงเป็นข่าวเด่น", type: "switch", defaultValue: false, optionalColumn: true },
      { name: "featured_sort_order", label: "ลำดับข่าวเด่น", type: "number", defaultValue: 0, optionalColumn: true },
      commonPublishedField,
      { name: "published_at", label: "วันที่เผยแพร่", type: "datetime" },
      { name: "view_count", label: "จำนวนเข้าชม", type: "number", defaultValue: 0, hidden: true },
    ],
  },
  {
    key: "announcements",
    label: "ประกาศวิทยาลัย",
    table: "announcements",
    permission: "announcements",
    titleField: "title",
    descriptionField: "content",
    categoryField: "category",
    statusField: "status",
    hrefField: "file_path",
    hrefFallback: "/news",
    normalizeHref: true,
    orderBy: "ORDER BY COALESCE(start_date, created_at) DESC, id DESC",
    createdAt: true,
    updatedAt: true,
    fields: [
      { name: "title", label: "หัวข้อประกาศ", type: "text", required: true },
      { name: "content", label: "รายละเอียดประกาศ", type: "textarea", span: "full" },
      { name: "category", label: "หมวดประกาศ", type: "text" },
      { name: "file_path", label: "ไฟล์แนบ / ลิงก์", type: "file", uploadFolder: "documents" },
      { name: "is_new", label: "แสดงเป็นประกาศใหม่", type: "switch", defaultValue: false },
      { name: "start_date", label: "วันที่เริ่มแสดง", type: "date" },
      { name: "end_date", label: "วันที่สิ้นสุด", type: "date" },
      commonPublishedField,
    ],
  },
  {
    key: "documents",
    label: "ดาวน์โหลดเอกสาร / แบบฟอร์ม",
    table: "documents",
    permission: "documents",
    titleField: "title",
    descriptionField: "description",
    categoryField: "department",
    statusField: "public_status",
    metricField: "download_count",
    metricSuffix: "ครั้ง",
    hrefTemplate: "/documents/{id}",
    hrefFallback: "/documents",
    orderBy: "ORDER BY is_featured DESC, download_count DESC, COALESCE(published_at, updated_at) DESC, id DESC",
    updatedAt: true,
    fields: [
      { name: "title", label: "ชื่อเอกสาร", type: "text", required: true },
      { name: "description", label: "คำอธิบาย", type: "textarea", span: "full" },
      { name: "content", label: "รายละเอียดเพิ่มเติม", type: "textarea", span: "full", optionalColumn: true },
      { name: "category_id", label: "หมวดเอกสาร", type: "select", optionsSource: "document_categories" },
      { name: "fiscal_year", label: "ปีงบประมาณ", type: "text", placeholder: "2569" },
      { name: "department", label: "ฝ่ายงาน / หน่วยงานเจ้าของเอกสาร", type: "text", placeholder: "งานทะเบียน / งานวิชาการ / งานการเงิน" },
      { name: "responsible_person", label: "ผู้รับผิดชอบ", type: "text" },
      { name: "file_path", label: "ไฟล์ / ลิงก์ดาวน์โหลด", type: "file", uploadFolder: "documents" },
      {
        name: "file_type",
        label: "ประเภทไฟล์",
        type: "select",
        defaultValue: "PDF",
        options: [
          { value: "PDF", label: "PDF" },
          { value: "DOCX", label: "Word / DOCX" },
          { value: "XLSX", label: "Excel / XLSX" },
          { value: "PPTX", label: "PowerPoint / PPTX" },
          { value: "ZIP", label: "ZIP" },
          { value: "IMAGE", label: "รูปภาพ" },
          { value: "LINK", label: "ลิงก์ภายนอก" },
          { value: "OTHER", label: "ไฟล์อื่นๆ" },
        ],
      },
      { name: "file_size", label: "ขนาดไฟล์ (KB)", type: "number", defaultValue: 0, optionalColumn: true },
      { name: "service_target", label: "กลุ่มผู้ใช้บริการ", type: "text", optionalColumn: true, placeholder: "นักเรียน นักศึกษา / ผู้ปกครอง / บุคลากร" },
      { name: "tags", label: "คำค้น / แท็ก", type: "text", optionalColumn: true, placeholder: "คำร้อง, แบบฟอร์ม, งานทะเบียน" },
      { name: "is_featured", label: "แสดงเป็นเอกสารแนะนำ", type: "switch", defaultValue: false, optionalColumn: true },
      { name: "sort_order", label: "ลำดับแสดงผล", type: "number", defaultValue: 0, optionalColumn: true },
      { name: "download_count", label: "จำนวนดาวน์โหลด", type: "number", defaultValue: 0, optionalColumn: true },
      { name: "public_status", label: "สถานะ", type: "select", defaultValue: "published", options: publishedStatusOptions },
      { name: "ita_related", label: "เกี่ยวข้องกับ ITA", type: "switch", defaultValue: false },
      { name: "ita_code", label: "รหัส OIT", type: "text", placeholder: "O9" },
      { name: "published_at", label: "วันที่เผยแพร่", type: "datetime" },
    ],
  },
  {
    key: "legal_items",
    label: "กฎหมายและระเบียบ",
    table: "legal_items",
    permission: "content_pages",
    titleField: "title",
    descriptionField: "description",
    categoryField: "category",
    statusField: "status",
    metricField: "fiscal_year",
    hrefFallback: "/content/laws",
    orderBy: "ORDER BY sort_order, COALESCE(effective_date, created_at) DESC, id DESC",
    createdAt: true,
    updatedAt: true,
    fields: [
      { name: "title", label: "ชื่อกฎหมาย / ระเบียบ", type: "text", required: true },
      { name: "category", label: "หมวด", type: "text", placeholder: "กฎหมายการศึกษา / ระเบียบวิทยาลัย" },
      { name: "description", label: "คำอธิบายสั้น", type: "textarea", span: "full" },
      { name: "content", label: "เนื้อหา / สาระสำคัญ", type: "textarea", span: "full", optionalColumn: true },
      { name: "fiscal_year", label: "ปีงบประมาณ / ปีการศึกษา", type: "text", optionalColumn: true, placeholder: "2569" },
      { name: "effective_date", label: "วันที่มีผล / วันที่ประกาศ", type: "date", optionalColumn: true },
      { name: "file_path", label: "ไฟล์แนบ", type: "file", uploadFolder: "documents", optionalColumn: true },
      { name: "source_url", label: "ลิงก์อ้างอิง", type: "text", optionalColumn: true },
      { name: "sort_order", label: "ลำดับ", type: "number", defaultValue: 0 },
      commonPublishedField,
    ],
  },
  {
    key: "procurement",
    label: "จัดซื้อจัดจ้าง / พัสดุ",
    table: "procurement",
    permission: "procurement",
    titleField: "title",
    descriptionField: "summary",
    categoryField: "type",
    statusField: "status",
    metricField: "budget",
    metricSuffix: "บาท",
    hrefTemplate: "/procurement/{id}",
    hrefFallback: "/procurement",
    orderBy: "WHERE COALESCE(type, '') <> 'รายงานงบทดลอง' ORDER BY COALESCE(published_at, updated_at) DESC, id DESC",
    updatedAt: true,
    fields: [
      { name: "title", label: "ชื่อรายการ", type: "text", required: true },
      { name: "summary", label: "สรุปสั้น", type: "textarea", span: "full", optionalColumn: true },
      { name: "content", label: "รายละเอียด", type: "textarea", span: "full", optionalColumn: true },
      { name: "type", label: "ประเภท", type: "text", placeholder: "ราคากลาง / แผนจัดซื้อจัดจ้าง" },
      { name: "fiscal_year", label: "ปีงบประมาณ", type: "text", placeholder: "2569" },
      { name: "department", label: "หน่วยงาน", type: "text", optionalColumn: true },
      { name: "budget", label: "งบประมาณ", type: "number" },
      { name: "file_path", label: "ไฟล์ / ลิงก์", type: "file", uploadFolder: "documents" },
      { name: "download_count", label: "จำนวนดาวน์โหลด", type: "number", defaultValue: 0, optionalColumn: true },
      commonPublishedField,
      { name: "published_at", label: "วันที่เผยแพร่", type: "datetime" },
    ],
  },
  {
    key: "trial_balance_reports",
    label: "รายงานงบทดลอง",
    table: "procurement",
    permission: "finance",
    titleField: "title",
    descriptionField: "summary",
    categoryField: "fiscal_year",
    statusField: "status",
    metricField: "download_count",
    metricSuffix: "ครั้ง",
    hrefTemplate: "/trial-balance/{id}",
    hrefFallback: "/trial-balance",
    orderBy: "WHERE type = 'รายงานงบทดลอง' ORDER BY fiscal_year DESC, COALESCE(published_at, updated_at) DESC, id DESC",
    updatedAt: true,
    fields: [
      { name: "title", label: "ชื่อรายงาน", type: "text", required: true },
      { name: "summary", label: "คำอธิบายสั้น", type: "textarea", span: "full", optionalColumn: true },
      { name: "content", label: "รายละเอียดรายงาน", type: "textarea", span: "full", optionalColumn: true },
      { name: "type", label: "ประเภทรายงาน", type: "text", hidden: true, defaultValue: "รายงานงบทดลอง" },
      { name: "fiscal_year", label: "ปีงบประมาณ", type: "text", required: true, placeholder: "2569" },
      { name: "department", label: "หน่วยงานรับผิดชอบ", type: "text", defaultValue: "งานการเงิน", optionalColumn: true },
      { name: "budget", label: "งบประมาณ / หมายเหตุเป็นตัวเลข", type: "number", defaultValue: 0 },
      { name: "file_path", label: "ไฟล์ / ลิงก์รายงาน", type: "file", uploadFolder: "documents" },
      { name: "download_count", label: "จำนวนดาวน์โหลด", type: "number", defaultValue: 0, optionalColumn: true },
      commonPublishedField,
      { name: "published_at", label: "วันที่เผยแพร่", type: "datetime" },
    ],
  },
  {
    key: "plans",
    label: "แผนและรายงาน",
    table: "plans_reports",
    permission: "plans",
    titleField: "title",
    descriptionField: "summary",
    categoryField: "report_type",
    statusField: "status",
    metricField: "fiscal_year",
    hrefTemplate: "/plans/{id}",
    hrefFallback: "/plans",
    orderBy: "ORDER BY COALESCE(published_at, updated_at) DESC, id DESC",
    updatedAt: true,
    fields: [
      { name: "title", label: "ชื่อแผน / รายงาน", type: "text", required: true },
      { name: "summary", label: "สรุปสั้น", type: "textarea", span: "full", optionalColumn: true },
      { name: "content", label: "รายละเอียด", type: "textarea", span: "full", optionalColumn: true },
      { name: "report_type", label: "ประเภท", type: "text", placeholder: "แผนปฏิบัติราชการ / SAR" },
      { name: "fiscal_year", label: "ปีงบประมาณ", type: "text", placeholder: "2569" },
      { name: "department", label: "หน่วยงาน", type: "text" },
      { name: "file_path", label: "ไฟล์ / ลิงก์", type: "file", uploadFolder: "documents" },
      { name: "download_count", label: "จำนวนดาวน์โหลด", type: "number", defaultValue: 0, optionalColumn: true },
      commonPublishedField,
      { name: "published_at", label: "วันที่เผยแพร่", type: "datetime" },
    ],
  },
  {
    key: "services",
    label: "บริการออนไลน์",
    table: "services",
    permission: "services",
    titleField: "service_name",
    descriptionField: "description",
    categoryField: "responsible_department",
    statusField: "status",
    metricField: "processing_time",
    hrefField: "service_url",
    hrefFallback: "/services",
    normalizeHref: true,
    orderBy: "ORDER BY service_name, id",
    fields: [
      { name: "service_name", label: "ชื่อบริการ", type: "text", required: true },
      { name: "description", label: "คำอธิบาย", type: "textarea", span: "full" },
      { name: "steps", label: "ขั้นตอนบริการ", type: "textarea", span: "full" },
      { name: "required_documents", label: "เอกสารที่ต้องใช้", type: "textarea", span: "full" },
      { name: "processing_time", label: "ระยะเวลาดำเนินการ", type: "text" },
      { name: "fee", label: "ค่าธรรมเนียม", type: "text" },
      { name: "service_url", label: "ลิงก์บริการ", type: "text" },
      { name: "responsible_department", label: "หน่วยงานรับผิดชอบ", type: "text" },
      commonActiveField,
    ],
  },
  {
    key: "ita",
    label: "Mapping ITA / OIT",
    table: "ita_mapping",
    permission: "ita",
    titleField: "ita_title",
    descriptionField: "note",
    categoryField: "category",
    statusField: "status",
    metricField: "ita_code",
    hrefField: "evidence_url",
    hrefFallback: "/ita",
    normalizeHref: true,
    orderBy: "ORDER BY ita_code, id",
    updatedAt: true,
    fields: [
      { name: "ita_code", label: "รหัส OIT", type: "text", required: true, placeholder: "O11" },
      { name: "ita_title", label: "หัวข้อ", type: "text", required: true },
      { name: "category", label: "หมวด", type: "text" },
      { name: "related_content_type", label: "ชนิดเนื้อหาที่เชื่อม", type: "text", placeholder: "procurement" },
      { name: "related_content_id", label: "ID เนื้อหาที่เชื่อม", type: "number" },
      { name: "fiscal_year", label: "ปีงบประมาณ", type: "text", placeholder: "2569" },
      { name: "responsible_person", label: "ผู้รับผิดชอบ", type: "text" },
      commonPublishedField,
      { name: "evidence_url", label: "ลิงก์หลักฐาน", type: "text" },
      { name: "note", label: "หมายเหตุ", type: "textarea", span: "full" },
    ],
  },
];

export function getAdminCrudConfig(moduleKey: string): AdminCrudModuleConfig | null {
  return adminCrudConfigs.find((config) => config.key === moduleKey) ?? null;
}
