import type { PodTemplate } from "./pod-template-card";

export const podTemplates: PodTemplate[] = [
  {
    id: "1",
    name: "Runpod Pytorch 2.1",
    description: "runpod/pytorch:2.1.0-py3.10-cuda11.8.0-devel-ubuntu22.04",
    image: "runpod/pytorch:2.1.0-py3.10-cuda11.8.0-devel-ubuntu22.04",
    author: "Runpod",
    authorType: "official",
    icon: "runpod",
    iconColor: "text-orange-500",
  },
  {
    id: "2",
    name: "Runpod Pytorch 2.2.0",
    description: "runpod/pytorch:2.2.0-py3.10-cuda12.1.1-devel-ubuntu22.04",
    image: "runpod/pytorch:2.2.0-py3.10-cuda12.1.1-devel-ubuntu22.04",
    author: "Runpod",
    authorType: "official",
    icon: "runpod",
    iconColor: "text-orange-500",
  },
  {
    id: "3",
    name: "Runpod Pytorch 2.4.0",
    description: "runpod/pytorch:2.4.0-py3.11-cuda12.4.1-devel-ubuntu22.04",
    image: "runpod/pytorch:2.4.0-py3.11-cuda12.4.1-devel-ubuntu22.04",
    author: "Runpod",
    authorType: "official",
    icon: "runpod",
    iconColor: "text-orange-500",
  },
  {
    id: "4",
    name: "Runpod Pytorch 2.8.0",
    description: "runpod/pytorch:1.0.2-cu1281-torch280-ubuntu2404",
    image: "runpod/pytorch:1.0.2-cu1281-torch280-ubuntu2404",
    author: "Runpod",
    authorType: "official",
    icon: "runpod",
    iconColor: "text-orange-500",
  },
  {
    id: "5",
    name: "ComfyUI",
    description: "runpod/comfyui:latest",
    image: "runpod/comfyui:latest",
    author: "Runpod",
    authorType: "official",
    icon: "comfyui",
    iconColor: "text-green-500",
  },
  {
    id: "6",
    name: "ComfyUI - Blackwell Edition (509...)",
    description: "runpod/comfyui:latest-5090",
    image: "runpod/comfyui:latest-5090",
    author: "Runpod",
    authorType: "official",
    icon: "comfyui",
    iconColor: "text-green-500",
  },
  {
    id: "7",
    name: "Runpod Pytorch 2.4.0 ROCm 6.1",
    description: "runpod/pytorch:2.4.0-py3.10-rocm6.1.0-ubuntu22.04",
    image: "runpod/pytorch:2.4.0-py3.10-rocm6.1.0-ubuntu22.04",
    author: "Runpod",
    authorType: "official",
    icon: "runpod",
    iconColor: "text-orange-500",
  },
  {
    id: "8",
    name: "Runpod Ubuntu 20.04",
    description: "runpod/base:0.7.0-ubuntu2004",
    image: "runpod/base:0.7.0-ubuntu2004",
    author: "Runpod",
    authorType: "official",
    icon: "runpod",
    iconColor: "text-red-500",
  },
];
